CREATE TABLE IF NOT EXISTS users (
    userID INT AUTO_INCREMENT,
    userName VARCHAR(128) NOT NULL,
    userPass VARCHAR(128) NOT NULL,
    currentTimestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (userID)
);
        
CREATE TABLE IF NOT EXISTS tasks (
    taskID INT NOT NULL AUTO_INCREMENT,
    taskName VARCHAR(32) NOT NULL,
    taskDesc VARCHAR(128) NOT NULL,
    taskDate DATETIME NOT NULL,
    taskCreate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    taskModify TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    userID INT,
    PRIMARY KEY (taskID),
    FOREIGN KEY (userID) REFERENCES users(userID)
);
        
CREATE TABLE IF NOT EXISTS passwords (
    passID INT NOT NULL AUTO_INCREMENT,
    passName VARCHAR(32) NOT NULL,
    passDesc VARCHAR(128) NOT NULL,
    passCreate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    userID INT,
    PRIMARY KEY (passID),
    FOREIGN KEY (userID) REFERENCES users(userID)
);
        
CREATE TABLE IF NOT EXISTS notes (
    noteID INT NOT NULL AUTO_INCREMENT,
    noteName VARCHAR(32) NOT NULL,
    noteDesc VARCHAR(256) NOT NULL,
    noteCreate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    userID INT,
    PRIMARY KEY (noteID),
    FOREIGN KEY (userID) REFERENCES users(userID)
);